feat: Added redis plugin
HF5-PROJECT/api pull request #14
Opened 2023-02-09 09:28 UTC by frederikpyt

## Description
1. Added fastify redis plugin, so we can cache stuff on our redis server

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2023-02-09 09:47 UTC, kristianbinau requested changes
Only small comment

2023-02-09 09:47 UTC, kristianbinau commented on src/plugins/redis.ts
> +        });
Add remember function: `redis.remember(String key, Callback function, Interger ttl): String`

2023-02-09 11:27 UTC, frederikpyt commented on src/plugins/redis.ts
> +        });
Done

2023-02-09 12:13 UTC, kristianbinau requested changes
Small fixes

2023-02-09 12:13 UTC, kristianbinau commented on src/plugins/redis.ts
> +            family: 4,
delete, default value.

2023-02-09 12:13 UTC, kristianbinau commented on src/plugins/redis.ts
> +            if (value) {
```suggestion
            if (value !== null) {
```

2023-02-09 15:42 UTC, frederikpyt commented on src/plugins/redis.ts
> +            family: 4,
OK

2023-02-10 07:19 UTC, kristianbinau approved these changes
It works! 🦺

2023-02-10 07:21 UTC, merged