feat: Added HotelInformation
HF5-PROJECT/api pull request #46
Opened 2023-03-02 16:01 UTC by kristianbinau

## Description

- Added HotelInformation
## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2023-03-02 16:10 UTC, kristianbinau commented
## Known problem:
Since "Information" doesn't have a plural form, it can be difficult to fit into our predefined structure.. I decided that it would make sense to still keep the "s" in some places to make it clearer that there's more than one `HotelInformation`.

2023-03-03 07:29 UTC, frederikpyt requested changes
For the tests to work after the suggested changes you may need to merge with master

2023-03-03 07:29 UTC, frederikpyt commented on src/modules/hotel/__test__/getHotelInformationsByHotel.test.ts
> +    });
```suggestion
import { prisma } from "../../../plugins/prisma";

describe("GET /api/hotel/:id/information", () => {
    const fastify = gloabl.fastify;
```

2023-03-03 07:29 UTC, frederikpyt commented on src/modules/hotel/__test__/getHotelInformationsByHotel.test.ts
> +    });
```suggestion
```

2023-03-03 07:29 UTC, frederikpyt commented on src/modules/hotel/hotel.schema.ts
> +    id: z.string(),
```suggestion
    id: z.number(),
```

2023-03-03 07:29 UTC, frederikpyt commented on src/modules/hotel/hotel.schema.ts
>      id: z.string(),
z.number ??

2023-03-03 07:29 UTC, frederikpyt commented on src/modules/hotel/information/__test__/createHotelInformation.test.ts
> +    let fastify: FastifyInstance;
```suggestion
import { User, Permission } from "@prisma/client";
import { prisma } from "../../../../plugins/prisma";
import { addTestUserAndPermission } from "../../../../utils/testHelper";

describe("POST /api/hotel/information", () => {
    const fastify = global.fastify;
```

2023-03-03 07:29 UTC, frederikpyt commented on src/modules/hotel/information/__test__/createHotelInformation.test.ts
> +    });
```suggestion
```

2023-03-03 07:29 UTC, frederikpyt commented on src/modules/hotel/information/__test__/createHotelInformation.test.ts
> +    });
```suggestion
```

2023-03-03 07:29 UTC, frederikpyt commented on src/modules/hotel/information/__test__/deleteHotelInformation.test.ts
> +    let fastify: FastifyInstance;
```suggestion
import { prisma } from "../../../../plugins/prisma";
import { addTestUserAndPermission } from "../../../../utils/testHelper";

describe("DELETE /api/hotel/information/:id", () => {
    const fastify = global.fastify;
```

2023-03-03 07:29 UTC, frederikpyt commented on src/modules/hotel/information/__test__/deleteHotelInformation.test.ts
> +    });
```suggestion
```

2023-03-03 07:29 UTC, frederikpyt commented on src/modules/hotel/information/__test__/deleteHotelInformation.test.ts
> +    });
```suggestion
```

2023-03-03 07:29 UTC, frederikpyt commented on src/modules/hotel/information/__test__/getAllHotelInformation.test.ts
> +    });
```suggestion
import { prisma } from "../../../../plugins/prisma";

describe("GET /api/hotel/information", () => {
    const fastify = global.fastify;
```

2023-03-03 07:29 UTC, frederikpyt commented on src/modules/hotel/information/__test__/getAllHotelInformation.test.ts
> +    });
```suggestion
```

2023-03-03 07:29 UTC, frederikpyt commented on src/modules/hotel/information/__test__/getHotelInformation.test.ts
> +    });
```suggestion
import { prisma } from "../../../../plugins/prisma";

describe("GET /api/hotel/information/:id", () => {
    const fastify = global.fastify;
```

2023-03-03 07:29 UTC, frederikpyt commented on src/modules/hotel/information/__test__/getHotelInformation.test.ts
> +    });
```suggestion
```

2023-03-03 07:29 UTC, frederikpyt commented on src/modules/hotel/information/__test__/updateHotelInformation.test.ts
> +    });
```suggestion
import { prisma } from "../../../../plugins/prisma";
import { addTestUserAndPermission } from "../../../../utils/testHelper";

describe("PUT /api/hotel/information", () => {
    const fastify = global.fastify;
    let accessToken: string;
    let accessTokenNoPermission: string
```

2023-03-03 07:29 UTC, frederikpyt commented on src/modules/hotel/information/__test__/updateHotelInformation.test.ts
> +    });
```suggestion
```

2023-03-03 07:29 UTC, frederikpyt commented on src/modules/hotel/information/information.schema.ts
> +    id: z.string(),
```suggestion
    id: z.number(),
```

2023-03-03 07:50 UTC, frederikpyt approved these changes

2023-03-03 07:51 UTC, merged